# Generated by Django 3.2.7 on 2021-09-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario_comentario',
            new_name='comentario',
        ),
    ]
